export { default as civilian } from "./civilian.svg";
export { default as coin } from "./coin.svg";
export { default as commerce } from "./commerce.svg";
export { default as guild } from "./guild.svg";
export { default as science } from "./science.svg";
export { default as military } from "./military.svg";
export { default as wonders } from "./wonders.svg";
export { default as save } from "./save.svg";
export { default as backArrow } from "./backArrow.svg";
